;;=== 日本語設定
(set-language-environment "Japanese")
(set-default-coding-systems 'utf-8)
(set buffer-file-coding-system 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

;; Keybindings (for macOS?)
(setq mac-command-key-is-meta nil)
(setq mac-option-modifier 'meta)
(global-set-key [(alt c)] 'kill-ring-save)
(global-set-key [(alt v)] 'yank)
(global-set-key [(alt x)] 'kill-region)
(global-set-key [(alt a)] 'mark-whole-buffer)
(global-set-key [(alt z)] 'undo)
(global-set-key [(alt f)] 'isearch-forward)
(global-set-key [(alt o)] 'find-file)
(global-set-key [(alt s)] 'save-buffer)
                                        ;(global-set-key [(alt p)] 'print-buffer)
                                        ;(global-set-key [(alt n)] 'make-frame-command)
                                        ;(global-set-key [(alt w)] 'delete-frame)
(global-set-key [(alt w)] 'kill-this-buffer)
(global-set-key [(alt m)] 'iconify-frame)
(global-set-key [(alt q)] 'save-buffers-kill-emacs)
(global-set-key [(alt .)] 'keyboard-quit)
(global-set-key (kbd "C-z") 'undo) ; Emacs default is bound to hide Emacs.
(define-key global-map [?¥] [?\\])  ;; ¥の代わりにバックスラッシュを入力する

;;=== mode selection
;;(setq default-major-mode 'text-mode)
(setq major-mode 'text-mode)
(setq auto-mode-alist
      (append '(("\\.h$" . fortran-mode)
      ("\\.m$" . objc-mode)
      ("\\.el$" . emacs-lisp-mode)
      ("\\.html$" . html-mode)
      ;;("\\.html$" . yahtml-mode)
      ("\\.f$" . fortran-mode)
      ("\\.F$" . fortran-mode)
      ("\\.f90$" . f90-mode)
      ("\\.F90$" . f90-mode)
      ("\\.pl$" . cperl-mode)
      ("\\.c$" . c-mode)
      ("\\.cpp$" . c++-mode)
      ("\\.css$" . css-mode)
      ("\\.js$" . javascript-mode)
      ;; ("\\.java$" . jde-mode)
      ("\\.tex$" . yatex-mode)
      ("\\.sty$" . yatex-mode)
      ("\\.ltx$" . yatex-mode)
      ("\\.java$" . java-mode)
      ("makefile" . makefile-mode)
      ("\\.py$" . python-mode)
      ("\\.gp$" . gnuplot-mode)
      ("\\.dot$" . graphviz-dot-mode)
      ("\\.org$" . org-mode)
      ("\\.yaml$" . yaml-mode)
      ("\\.yml$" . yaml-mode)
      ("\\.md$" . markdown-mode)
      ("\\.toml$" . conf-toml-mode)
      )))

(modify-coding-system-alist 'file "\\.rst\\'" 'utf-8)
(modify-coding-system-alist 'file "\\.org\\'" 'utf-8)
(modify-coding-system-alist 'file "\\.md\\'" 'utf-8)

;;=== don't use tab globally
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)

;;=== global outline-minor-mode-prefix setting ========================
(setq outline-minor-mode-prefix "\C-c\C-o")

;; Disable automatic formatting on save
(setq prelude-format-on-save nil)
